services:

  db:
    image: postgres:16-alpine
    container_name: esme_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mot_de_passe
      POSTGRES_DB: esme_inge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d esme_inge"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: esme_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://myuser:mot_de_passe@db:5432/esme_inge
      FLASK_ENV: development
      FLASK_DEBUG: 1
    ports:
      - "5009:5000"
    volumes:
      - ./backend:/app
      - ./backend/migrations:/app/migrations
    command: >
      sh -c "python init_db.py &&
             flask run --host=0.0.0.0 --port=5009"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: esme_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5009
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
